# Generated by Django 3.0.3 on 2023-02-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('nonstudent', '0001_initial'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrents',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rents',
            name='user_id',
        ),
        migrations.AddField(
            model_name='historicalrents',
            name='nonstudent_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nonstudent.NonStudents'),
        ),
        migrations.AddField(
            model_name='historicalrents',
            name='ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalrents',
            name='student_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student.Students'),
        ),
        migrations.AddField(
            model_name='rents',
            name='nonstudent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonstudent.NonStudents'),
        ),
        migrations.AddField(
            model_name='rents',
            name='ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rents',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
    ]
