# Generated by Django 3.0.3 on 2023-02-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20230201_1203'),
        ('rent', '0002_auto_20230201_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrents',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalrents',
            name='listing_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='listing.Listings'),
        ),
        migrations.AlterField(
            model_name='historicalrents',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rents',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rents',
            name='listing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Listings'),
        ),
        migrations.AlterField(
            model_name='rents',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
