# Generated by Django 3.0.3 on 2023-02-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20230202_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrents',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='rents',
            name='ref',
        ),
    ]
