# Generated by Django 3.0.3 on 2023-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudents',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicalstudents',
            name='student_id',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
