# Generated by Django 3.0.3 on 2023-01-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nonstudent', '0001_initial'),
        ('student', '0001_initial'),
        ('auth_account', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('homeowners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homeowners_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeowners.Homeowners'),
        ),
        migrations.AddField(
            model_name='user',
            name='nonstudent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonstudent.NonStudents'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
